// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwOcASScO-TRIbMSsufogp_e01PB25IAk',
    appId: '1:549893694825:web:ec8ec4eb13bf18d0ec09f8',
    messagingSenderId: '549893694825',
    projectId: 'apgcl-leave',
    authDomain: 'apgcl-leave.firebaseapp.com',
    storageBucket: 'apgcl-leave.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrd7omrjkADjZRt0ZiXgMJb3sLq-O5_c0',
    appId: '1:549893694825:android:b697893cc88de119ec09f8',
    messagingSenderId: '549893694825',
    projectId: 'apgcl-leave',
    storageBucket: 'apgcl-leave.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTczUESeUxLZb32SrJqxKIr-dIUcM8nJM',
    appId: '1:549893694825:ios:f5ef9e0f448caa44ec09f8',
    messagingSenderId: '549893694825',
    projectId: 'apgcl-leave',
    storageBucket: 'apgcl-leave.appspot.com',
    iosClientId: '549893694825-g870lpadmd8ten44o0trlc0b4gsbnufa.apps.googleusercontent.com',
    iosBundleId: 'com.example.leaveManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTczUESeUxLZb32SrJqxKIr-dIUcM8nJM',
    appId: '1:549893694825:ios:aa97a490957f60e1ec09f8',
    messagingSenderId: '549893694825',
    projectId: 'apgcl-leave',
    storageBucket: 'apgcl-leave.appspot.com',
    iosClientId: '549893694825-1bdnjjg5j83lqe2hg1tf19ec6qf94kco.apps.googleusercontent.com',
    iosBundleId: 'com.example.leaveManagementSystem.RunnerTests',
  );
}
